name: "DLRM"

feature_embedding_dims: 32 # 1 fieldあたりのembedding次元数

# user behavior encoder
behavior_encoder_type: mean # [mean, din_attention]
behavior_din_hidden_dims: []
behavior_din_activation: dice
behavior_din_normalize: null
behavior_din_dropout: 0.0
behavior_din_use_softmax: false

# DLRMのdense feature をエンコードするMLP
dense_hidden_features_list: [128, 64] # Dense Feature MLPの隠れ層のユニット数
dense_activation: relu # Dense Feature MLPの活性化関数
dense_normalize: batch # Dense Feature MLPの正規化手法
dense_dropout: 0.5

# DLRMのtop MLP(dense featureとsparse feature)
top_hidden_features_list: [128, 64] # top MLPのDNNの隠れ層のユニット数
top_activation: relu # top MLPの活性化関数
top_normalize: batch # top MLPの正規化手法
top_dropout: 0.5
