version: 2
updates:
  # python
  - package-ecosystem: "uv"
    directories:
      - "/libs/*"
      - "/projects/*"
      - "/apps/*"
      - "/apps/*/samples"
    schedule:
      interval: "monthly"
    groups:
      minor-patch:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
  # github actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
