[project]
name = "job-runner"
version = "0.1.0"
description = "Command line utilities to run ml training job"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["loguru~=0.7.3", "pydantic~=2.10.4", "pydantic-settings~=2.7.1"]

[dependency-groups]
dev = ["pytest~=8.3.4", "mypy~=1.14.1"]
lint = ["ruff~=0.8.4"]

[tool.ruff]
target-version = "py312"
line-length = 100

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
python_version = "3.12"
exclude = [".venv"]
plugins = ["pydantic.mypy"]

follow_imports = "silent"
warn_redundant_casts = true
warn_unused_ignores = true
disallow_any_generics = true
no_implicit_reexport = true
disallow_untyped_defs = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
