defaults:
  - _self_
  - hydra: default
  - model: dlrm

save_dir: ./results/
debug: true

device:
  accelerator: gpu
  accelerator_no: 0
  num_workers: 4
  float16: true

data:
  batch_size: 512
  max_seq_len: 50
  neg_sample_size: 8 # training時の負例数
  eval_top_k: 30 # nDCGやMRRを評価する上位K

optimizer:
  lr: 0.00001
  gradient_clip_val: 1.0
  weight_decay: 0
  lr_scheduler: # cosine annealingの設定
    step_unit: epoch # 学習率を減衰させる単位
    frequency: 1 # 学習率を減衰させる頻度
    t_initial: 100 # 学習率を減衰させるstep数, このstep後min_lrに到達する
    warmup_t: 3 # warmupのstep数。このstep後にlrに到達し、その後は減衰する
    warmup_lr_init: 0.000001 # warmupの開始時の学習率
    lr_min: 0.0000001 # 最小の学習率。この値まで減衰させる
    cycle_limit: 1 # restartの回数, 1: 通常のcosine annealing, 2以上: cosine annealing with restarts

log:
  log_every_n_steps: 100
