blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/haru-256/ml-sandbox/issues/new?template=feature_request.md
    about: Feature requests are welcome. Please report here.
  - name: Bug Report
    url: https://github.com/haru-256/ml-sandbox/issues/new?template=bug_report.md
    about: Bug reports are welcome. Please report here.
