services:
  job:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["tail", "-f", "/dev/null"]
    platform: linux/amd64
    image: ${IMAGE_URI:?error}
    environment:
      - GCS_PATH=${GCS_PATH:?error}
      - EXPERIMENT_NAME=${EXPERIMENT_NAME:?error}
    volumes:
      - ${MOUNTED_GCS_PATH:?error}:${MOUNTED_GCS_PATH:?error}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
