services:
  job:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        - ml_sandbox_libs=../../libs/ml_sandbox_libs
    command: ["tail", "-f", "/dev/null"]
    platform: linux/amd64
    image: ${IMAGE_URI:?error}
    environment:
      - WANDB_API_KEY=${WANDB_API_KEY:?WANDB_API_KEY is required}
      - EXPERIMENT_NAME=${EXPERIMENT_NAME:-local-experiment}
      - GCS_PATH=${GCS_PATH:-/tmp/gcs}
    volumes:
      - ${MOUNTED_GCS_PATH:-/tmp/gcs}:${MOUNTED_GCS_PATH:-/tmp/gcs}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
