[project]
name = "sasrec"
version = "0.1.0"
description = "Sequential Recommendation"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
  "lightning~=2.5.0.post0",
  "torchmetrics~=1.6.1",
  "datasets~=3.3.2",
  "numpy~=2.2.3",
  "polars~=1.23.0",
  "tensorboard~=2.19.0",
  "torchinfo~=1.8.0",
  "loguru~=0.7.3",
]

[project.optional-dependencies]
cpu = ["torch==2.5.1"]
gpu = ["torch==2.5.1"]

[dependency-groups]
dev = [
  "notebook~=7.3.2",
  "pytest~=8.3.4",
  "mypy~=1.15.0",
  "ipywidgets>=8.1.5",
  "tqdm~=4.67.1",
]
lint = ["ruff~=0.9.5"]

[tool.uv]
conflicts = [[{ extra = "cpu" }, { extra = "gpu" }]]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu-mac", extra = "cpu", marker = "platform_system == 'macOS'" },
  { index = "pytorch-cpu", extra = "cpu", marker = "platform_system != 'macOS'" },
  { index = "pytorch-gpu", extra = "gpu" },
]

[[tool.uv.index]]
name = "pytorch-cpu-mac"
url = "https://pypi.python.org/simple"
explicit = true

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-gpu"
url = "https://download.pytorch.org/whl/cu121"
explicit = true

[tool.ruff]
target-version = "py312"
line-length = 100
extend-exclude = ["notebooks"]

[tool.ruff.lint]
extend-select = ["I"]

[tool.mypy]
python_version = "3.12"
exclude = [".venv"]
disable_error_code = ["import-untyped"]

[[tool.mypy.overrides]]
module = [
  "torch.*",
  "lightning.*",
  "torchinfo.*",
  "torchmetrics.*",
  ".*",
  "config.*",
  "utils.*",
]
ignore_missing_imports = true
